export const HOME_SWIPER = 'home_swiper'
export const HOME_NAV = 'home_nav'
export const HOME_SHOP_LIST= 'home_shop_list'
export const RECOMMEND_SHOP_LIST= 'recommend_shop_list'
export const SEARCH_GOODS= 'search_goods'
